# Generated by Django 5.1.1 on 2024-09-23 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Polls Category',
                'verbose_name_plural': 'Polls Categories',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Poll Deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Confirmed')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_polls', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField(verbose_name='Option')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll', verbose_name='Poll')),
            ],
            options={
                'verbose_name': 'Poll Option',
                'verbose_name_plural': 'Polls Options',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='polls.poll', verbose_name='Poll')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='PollCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='polls.category', verbose_name='Category')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='polls.poll', verbose_name='Poll')),
            ],
        ),
        migrations.CreateModel(
            name='RankedVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('points', models.IntegerField(verbose_name='Points')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='polls.option', verbose_name='Option')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='polls.poll', verbose_name='Poll')),
            ],
            options={
                'verbose_name': 'Ranked Vote',
                'verbose_name_plural': 'Ranked Votes',
            },
        ),
        migrations.CreateModel(
            name='SimpleVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='polls.option', verbose_name='Option')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='polls.poll', verbose_name='Poll')),
            ],
            options={
                'verbose_name': 'Simple Vote',
                'verbose_name_plural': 'Simple Votes',
            },
        ),
    ]
