# Generated by Django 5.1.1 on 2024-09-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankedvote',
            name='is_preferential',
            field=models.BooleanField(default=False, verbose_name='Preferential'),
        ),
    ]
