# Generated by Django 5.1.1 on 2024-09-28 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_comment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Dislikes Count'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes Count'),
        ),
        migrations.AddField(
            model_name='poll',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Comments Count'),
        ),
        migrations.AlterField(
            model_name='rankedvote',
            name='points',
            field=models.PositiveSmallIntegerField(verbose_name='Points'),
        ),
        migrations.CreateModel(
            name='CommentDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='polls.comment', verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Comment Dislikes',
                'verbose_name_plural': 'Comments Dislikes',
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_likes', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='polls.comment', verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Comment Likes',
                'verbose_name_plural': 'Comments Likes',
            },
        ),
    ]
