# Generated by Django 5.1.1 on 2024-09-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_comment_dislikes_count_comment_likes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='preferential_votes',
            field=models.JSONField(blank=True, null=True, verbose_name='Preferential Votes'),
        ),
        migrations.AddField(
            model_name='option',
            name='ranked_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Ranked Points'),
        ),
        migrations.AddField(
            model_name='option',
            name='simple_votes',
            field=models.PositiveIntegerField(default=0, verbose_name='Simple Votes'),
        ),
    ]
